version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "12:30"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
