import { NextPage } from 'next'
import Head from 'next/head';
import React from 'react'

const Bedrift: NextPage = () => {
    return (
        <>
            <Head>
                <title>For Bedrifter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <h1>Bedrifter!</h1>


            </main>
        </>
    )
}

export default Bedrift;
