import { MemberCard } from '@/components/MemberCard'
import Head from 'next/head'

import membersJSON from "../../constants/members.json"


export default function Home() {

  const members = membersJSON.members;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <h1>Main page</h1>
       
      </main>
    </>
  )
}
