import { MemberCard } from '@/components/MemberCard'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MemberCard name='Morten' role='Promo Leder' attributes={["hr", "leder"]} study="Elektroingeniør - 3.året" description='Promo ansvarlig for Start Gjøvik! '/>
      </main>
    </>
  )
}
