import { MemberCard } from '@/components/MemberCard';
import { MemberType } from '@/constants/members';
import { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react'
import events from './api/events';

const Om_oss: NextPage = () => {

    const [members, setMembers] = useState<MemberType[]>([]);

    const fetchMembers= async () => {
        const response = await fetch("/api/members");
        const data = await response.json();
        setMembers(data);

    }

    useEffect(() => { fetchMembers() }, [])




    return (
        <>
            <Head>
                <title>Events</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <h1>Events!</h1>

                {members.map((member) => (
                    <MemberCard description={member.description} name={member.name} role={member.role} study={member.study} attributes={member.attribute} key={member.id} />
                )) ?? null}

            </main>


        </>
    )
}

export default Om_oss;
